### PR TITLE
Use == instead of - to set triton version in pip and upgrade to 3.2.0

### PR DESCRIPTION
**Pull request by skimberk**
Should fix the issue seen in #32 where the Colab notebook doesn't install the older version of `triton` (`3.1.0`) and instead uses the version that comes pre-installed on Colab (`3.4.0` at the time of me writing this), causing the error.

It seems the `triton` install command was broken (at least on Colab), and changing the `triton-3.1.0` to `triton==3.1.0` seems to fix it.

As is, the `!pip install triton-3.1.0` command gives the following output:
```
ERROR: Could not find a version that satisfies the requirement triton-3.1.0 (from versions: none)
ERROR: No matching distribution found for triton-3.1.0
```

I wonder if there was some change to `pip` or the way `triton` is distributed? Since I'm guessing (hoping) it hasn't been broken since #25.

Also, as noted by @Bakameow in https://github.com/srush/Triton-Puzzles/issues/32#issuecomment-3210623072 it seems like just reverting to `3.1.0` has its own issues (pasted the error I saw below) so I also updated it to `3.2.0`, which seems to work!

Error message when running introduction demo with `3.1.0` on Colab:
```
AttributeError: type object 'JITFunction' has no attribute '_type_of'
```

I tested by creating a new Colab notebook with the updated code and making sure the packages installed and the first few code blocks ran without error.

@srush @mark14wu @Jokeren

### CODE REVIEW

**Review by Jokeren — APPROVED** [review]

**Comment by mark14wu** [comment]
@Jokeren It's approved but still open?
